AWS_UPLOAD_BUCKET = "africafootball79"

AWS_UPLOAD_USERNAME = "africa_web_user"

AWS_UPLOAD_GROUP = "Af_AwesomeGroup"

AWS_UPLOAD_REGION = "Asia Pacific (Mumbai)"

AWS_UPLOAD_ACCESS_KEY_ID = "AKIASZEXQ3K5I3VVSTG5"

AWS_UPLOAD_SECRET_KEY = "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"