# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-15 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
