# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-15 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hostinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('match', models.CharField(max_length=500)),
                ('nation_flag', models.CharField(max_length=500)),
                ('team', models.CharField(max_length=100)),
                ('team_flag', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WinnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
