# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-15 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teaminfo_winnerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='info',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
