# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-15 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180915_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamInfo',
            new_name='TeamInfo1',
        ),
    ]
