# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-15 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180915_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostInfo',
        ),
        migrations.DeleteModel(
            name='TeamInfo1',
        ),
        migrations.DeleteModel(
            name='WinnerInfo',
        ),
    ]
